### ISSUE TITLE
2023년 1월 15일 일요일 스터디 쓰레드

### ISSUE THREAD

**Issue by juno-junho** [konkuk-tech-course/attendance-checker#24]
위치: 스타벅스 군자사거리점 
출석 확인을 위해 comment를 달아주세요😊

**Comment by juno-junho** [comment]
도착시간: 11:35
- unit testing 스터디 진행
- Mockito에 대한 간략한 학습

**Comment by yummygyudon** [comment]
도착시간 : 16:00

- 파이콘 업무
- 자소서
- 월요일 스터디 내용(네트워크+OS) 학습
